In [127]:
import pandas as pd

In [128]:
df = pd.read_csv('../data/indicador_bienestar.csv', encoding='latin-1')
df

,valores y media,sexo,periodo,características sociodemográficas,Satisfacción con la vida,Valor de la vida,Satisfacción con el tiempo de ocio,Satisfacción con la vivienda y el entorno,Satisfacción con la economía doméstica,Estado de ánimo,Relaciones personales,Confianza en las personas,Confianza en los poderes públicos
0,Bajo,Hombre,2024,-Araba/Álava (residencia),3.60,2.80,11.30,2.30,6.00,3.80,2.70,12.60,49.10
1,Bajo,Hombre,2024,-Bizkaia (residencia),4.80,3.50,14.50,3.80,7.60,7.00,1.80,10.40,41.00
2,Bajo,Hombre,2024,-Gipuzkoa (residencia),5.00,3.00,11.40,3.50,5.90,5.50,2.80,11.10,47.30
3,Bajo,Hombre,2024,-35-49,4.70,3.70,21.40,3.60,7.20,5.60,3.10,12.90,47.50
4,Bajo,Hombre,2024,-50-64,6.10,4.10,15.90,4.30,11.00,7.10,3.50,12.80,47.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,MEDIA,Mujer,2024,-Superiores profesionales,7.26,7.67,6.15,7.08,6.93,6.11,7.56,6.46,4.25
100,MEDIA,Mujer,2024,-Superiores generales,7.63,8.00,6.33,7.18,7.31,6.38,7.61,6.94,4.81
101,MEDIA,Mujer,2024,-Ocupados,7.48,7.91,5.91,7.11,7.13,6.20,7.55,6.60,4.56
102,MEDIA,Mujer,2024,-Parados,7.13,7.60,6.93,6.99,5.72,5.96,7.25,6.11,4.37
103,MEDIA,Mujer,2024,-Inactivos,7.28,7.57,7.34,7.24,6.94,6.36,7.47,6.48,4.71

In [129]:
df.rename(columns={'valores y media': 'nv_general',
                   'características sociodemográficas': 'caract',
                   'Satisfacción con la vida': 'satis_vida',
                   'Valor de la vida': 'valor_vida',
                   'Satisfacción con el tiempo de ocio': 'satis_tmp_ocio',
                   'Satisfacción con la vivienda y el entorno': 'satis_vivienda',
                   'Satisfacción con la economía doméstica': 'satis_economica',
                   'Estado de ánimo': 'animo',
                   'Relaciones personales': 'relaciones',
                   'Confianza en las personas': 'confi_personas',
                   'Confianza en los poderes públicos': 'confi_politica'
                    },
          inplace=True)

In [130]:
df.drop(columns='periodo', inplace=True)

In [131]:
df = df[df['nv_general'] != 'MEDIA']

In [132]:
print(df['nv_general'].unique())
mapeo = {'Bajo': 0, 'Medio': 1, 'Alto': 2}

['Bajo' 'Medio' 'Alto']

In [133]:
df.loc[:, 'nv_general'] = df['nv_general'].map(mapeo)
df

,nv_general,sexo,caract,satis_vida,valor_vida,satis_tmp_ocio,satis_vivienda,satis_economica,animo,relaciones,confi_personas,confi_politica
0,0,Hombre,-Araba/Álava (residencia),3.6,2.8,11.3,2.3,6.0,3.8,2.7,12.6,49.1
1,0,Hombre,-Bizkaia (residencia),4.8,3.5,14.5,3.8,7.6,7.0,1.8,10.4,41.0
2,0,Hombre,-Gipuzkoa (residencia),5.0,3.0,11.4,3.5,5.9,5.5,2.8,11.1,47.3
3,0,Hombre,-35-49,4.7,3.7,21.4,3.6,7.2,5.6,3.1,12.9,47.5
4,0,Hombre,-50-64,6.1,4.1,15.9,4.3,11.0,7.1,3.5,12.8,47.0
...,...,...,...,...,...,...,...,...,...,...,...,...
73,2,Mujer,-Superiores profesionales,54.5,62.3,30.6,41.0,38.4,14.4,63.6,31.8,4.0
74,2,Mujer,-Superiores generales,64.9,71.4,35.0,45.3,52.3,19.5,69.1,39.8,6.1
75,2,Mujer,-Ocupados,59.4,68.9,27.0,42.9,44.0,16.6,66.0,34.0,6.2
76,2,Mujer,-Parados,45.1,61.4,44.4,41.9,27.4,14.7,50.7,31.2,7.4
77,2,Mujer,-Inactivos,53.6,60.4,56.6,48.1,45.1,22.8,63.8,33.9,5.8

In [134]:
df['sexo'] = df['sexo'].map({'Hombre': 0, 'Mujer': 1})
df

C:\Users\detla\AppData\Local\Temp\ipykernel_12452\4054407341.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sexo'] = df['sexo'].map({'Hombre': 0, 'Mujer': 1})

,nv_general,sexo,caract,satis_vida,valor_vida,satis_tmp_ocio,satis_vivienda,satis_economica,animo,relaciones,confi_personas,confi_politica
0,0,0,-Araba/Álava (residencia),3.6,2.8,11.3,2.3,6.0,3.8,2.7,12.6,49.1
1,0,0,-Bizkaia (residencia),4.8,3.5,14.5,3.8,7.6,7.0,1.8,10.4,41.0
2,0,0,-Gipuzkoa (residencia),5.0,3.0,11.4,3.5,5.9,5.5,2.8,11.1,47.3
3,0,0,-35-49,4.7,3.7,21.4,3.6,7.2,5.6,3.1,12.9,47.5
4,0,0,-50-64,6.1,4.1,15.9,4.3,11.0,7.1,3.5,12.8,47.0
...,...,...,...,...,...,...,...,...,...,...,...,...
73,2,1,-Superiores profesionales,54.5,62.3,30.6,41.0,38.4,14.4,63.6,31.8,4.0
74,2,1,-Superiores generales,64.9,71.4,35.0,45.3,52.3,19.5,69.1,39.8,6.1
75,2,1,-Ocupados,59.4,68.9,27.0,42.9,44.0,16.6,66.0,34.0,6.2
76,2,1,-Parados,45.1,61.4,44.4,41.9,27.4,14.7,50.7,31.2,7.4
77,2,1,-Inactivos,53.6,60.4,56.6,48.1,45.1,22.8,63.8,33.9,5.8

In [135]:
df.loc[:, 'caract'] = df['caract'].str.replace(r'^-', '', regex=True)
df

,nv_general,sexo,caract,satis_vida,valor_vida,satis_tmp_ocio,satis_vivienda,satis_economica,animo,relaciones,confi_personas,confi_politica
0,0,0,Araba/Álava (residencia),3.6,2.8,11.3,2.3,6.0,3.8,2.7,12.6,49.1
1,0,0,Bizkaia (residencia),4.8,3.5,14.5,3.8,7.6,7.0,1.8,10.4,41.0
2,0,0,Gipuzkoa (residencia),5.0,3.0,11.4,3.5,5.9,5.5,2.8,11.1,47.3
3,0,0,35-49,4.7,3.7,21.4,3.6,7.2,5.6,3.1,12.9,47.5
4,0,0,50-64,6.1,4.1,15.9,4.3,11.0,7.1,3.5,12.8,47.0
...,...,...,...,...,...,...,...,...,...,...,...,...
73,2,1,Superiores profesionales,54.5,62.3,30.6,41.0,38.4,14.4,63.6,31.8,4.0
74,2,1,Superiores generales,64.9,71.4,35.0,45.3,52.3,19.5,69.1,39.8,6.1
75,2,1,Ocupados,59.4,68.9,27.0,42.9,44.0,16.6,66.0,34.0,6.2
76,2,1,Parados,45.1,61.4,44.4,41.9,27.4,14.7,50.7,31.2,7.4
77,2,1,Inactivos,53.6,60.4,56.6,48.1,45.1,22.8,63.8,33.9,5.8

In [137]:
df.loc[:, 'caract'] = df['caract'].str.replace(r'/.*|\(.*', '', regex=True).str.strip()
df

,nv_general,sexo,caract,satis_vida,valor_vida,satis_tmp_ocio,satis_vivienda,satis_economica,animo,relaciones,confi_personas,confi_politica
0,0,0,Araba,3.6,2.8,11.3,2.3,6.0,3.8,2.7,12.6,49.1
1,0,0,Bizkaia,4.8,3.5,14.5,3.8,7.6,7.0,1.8,10.4,41.0
2,0,0,Gipuzkoa,5.0,3.0,11.4,3.5,5.9,5.5,2.8,11.1,47.3
3,0,0,35-49,4.7,3.7,21.4,3.6,7.2,5.6,3.1,12.9,47.5
4,0,0,50-64,6.1,4.1,15.9,4.3,11.0,7.1,3.5,12.8,47.0
...,...,...,...,...,...,...,...,...,...,...,...,...
73,2,1,Superiores profesionales,54.5,62.3,30.6,41.0,38.4,14.4,63.6,31.8,4.0
74,2,1,Superiores generales,64.9,71.4,35.0,45.3,52.3,19.5,69.1,39.8,6.1
75,2,1,Ocupados,59.4,68.9,27.0,42.9,44.0,16.6,66.0,34.0,6.2
76,2,1,Parados,45.1,61.4,44.4,41.9,27.4,14.7,50.7,31.2,7.4
77,2,1,Inactivos,53.6,60.4,56.6,48.1,45.1,22.8,63.8,33.9,5.8